### PR TITLE
Allow region processing.

### PR DESCRIPTION
**Pull request by mattfidler**
This should allow region processing.

### CODE REVIEW

**Comment by cofi** [comment]
Thank you for the pull request.

But before I actually merge it: Please add documentation to the functions and maybe to the README.
Because vim doesn't define C-a/C-x in visual mode I'm not sure about how it is supposed to work and I bet so will be others.

**Comment by mattfidler** [comment]
You will have to let me know what it does in visual mode since I don't use evil and don't intend to. 

In emacs mode it renumbered all of the numbers found in a region. Is this true in visual mode?

Once you confirm, I can update the documentation.

**Comment by cofi** [comment]
Ah, sorry I assumed you'd be an evil user.

evil's visual mode selection is effectlvely the emacs region so it will behave the same.
My problem is/was that the behavior might not be expected so I want it documented :)

**Comment by mattfidler** [comment]
No.  I'm an ergoemacs-mode user :)  Still don't use emacs keys.

**Comment by mattfidler** [comment]
Do you have to do something to use evil visual mode?

**Comment by mattfidler** [comment]
My documentation assumes that you don't have to define any special keys to use the increment/deincrement functions for the region.

**Comment by cofi** [comment]
Thank you!

**Pull request merged**
